#
# Module manifest for module 'Daj'
#
# Generated by: MrClutter
#
# Generated on: 2022-07-21
#

@{

    RootModule = 'Daj.psm1'
    ModuleVersion = '1.1.1'
    CompatiblePSEditions = 'Desktop', 'Core'
    GUID = '381904c7-e3ba-4cdb-aa45-462f1f1e0f34'
    Author = 'MrClutter'
    CompanyName = '---'
    Copyright = '(c) 2022 MrClutter. All rights reserved.'
    Description = 'Daj mod for Get-ADUser'
    FunctionsToExport = @('Daj-user', 'Daj-Group', 'Da')
    CmdletsToExport = @('')
    VariablesToExport = @('')
    AliasesToExport = @('Daj')
    PrivateData = @{
        PSData = @{}
    }
}
